name: opensubtitles_api
description: A new Flutter package project.
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  dio: ^5.6.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.12
  flutter_lints:
    git: https://github.com/Sockitos/flutter_lints/
  freezed: ^2.5.7
  json_serializable: ^6.8.0
